export const asiento = [
  {
    id: 1,
    Descripcion: 'Apertura',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 2,
    Descripcion: 'Compras ',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 3,
    Descripcion: 'Compras - Importaciones',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 4,
    Descripcion: 'Compras No Gravadas',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 5,
    Descripcion: 'Compras - Detracciones',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 6,
    Descripcion: 'Letras por Pagar',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 7,
    Descripcion: 'Ventas',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 8,
    Descripcion: 'Ventas - Exportaciones',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 9,
    Descripcion: 'Ventas - Inafectas',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 10,
    Descripcion: 'Canje',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 11,
    Descripcion: 'Letras por Cobrar',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 12,
    Descripcion: 'Recibo por Honorarios',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 13,
    Descripcion: 'Caja Efectivo',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 14,
    Descripcion: 'Ingresos BCP M.N.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 15,
    Descripcion: 'Ingresos BCP M.E.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 16,
    Descripcion: 'Ingresos Scotiabank M.N.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 17,
    Descripcion: 'Ingresos Scotiabank M.E.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 18,
    Descripcion: 'Egresos BCP M.N.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 19,
    Descripcion: 'Egresos BCP M.E.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 20,
    Descripcion: 'Egresos Scotiabank M.N.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 21,
    Descripcion: 'Egresos Scotiabank M.E.',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 22,
    Descripcion: 'Pago con Tarjetas',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 23,
    Descripcion: 'Rendicion de Fondo Fijo',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 24,
    Descripcion: 'Rendicion de Cuenta',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 25,
    Descripcion: 'Inventario - Ingreso',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 26,
    Descripcion: 'Inventario - Salida',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 27,
    Descripcion: 'Regular. Inventario - Ingreso',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 28,
    Descripcion: 'Regular. Inventario - Salida',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 29,
    Descripcion: 'Asiento de Planillas',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 30,
    Descripcion: 'Provision de Depreciación',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 31,
    Descripcion: 'Provision de CTS',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 32,
    Descripcion: 'Provision de Vacaciones',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 33,
    Descripcion: 'Provision de Alquileres',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 34,
    Descripcion: 'Costo de Producción',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 35,
    Descripcion: 'Costo de Ventas',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 36,
    Descripcion: 'Ajustes por Dif. de Cambio',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 37,
    Descripcion: 'Asientos de Cierre',
    estado: 1,
    created_at: null,
    updated_at: null,
  },
];
