export const costos = [
  {
    cc_id: 1,
    cc_des: 'Administración',
    cc_est: 1,
    cta_id_debe: 9411111,
    cta_id_haber: 7911111,
    created_at: null,
    updated_at: null,
  },
  {
    cc_id: 2,
    cc_des: 'Ventas',
    cc_est: 1,
    cta_id_debe: 9511111,
    cta_id_haber: 7911111,
    created_at: null,
    updated_at: null,
  },
  {
    cc_id: 3,
    cc_des: 'Finanzas',
    cc_est: 1,
    cta_id_debe: null,
    cta_id_haber: null,
    created_at: null,
    updated_at: null,
  },
  {
    cc_id: 4,
    cc_des: 'Logística',
    cc_est: 1,
    cta_id_debe: null,
    cta_id_haber: null,
    created_at: null,
    updated_at: null,
  },
  {
    cc_id: 5,
    cc_des: 'TI',
    cc_est: 1,
    cta_id_debe: null,
    cta_id_haber: null,
    created_at: null,
    updated_at: null,
  },
];
