export const moneda = [
  {
    codigo: 'AED',
    mon_des: 'UAE Dirham',
    pais: 'Emiratos Árabes Unidos',
    mon_est: 1,
  },
  {
    codigo: 'AFN',
    mon_des: 'Afghani',
    pais: 'Afganistán',
    mon_est: 1,
  },
  {
    codigo: 'ALL',
    mon_des: 'Lek',
    pais: 'Albania',
    mon_est: 1,
  },
  {
    codigo: 'AMD',
    mon_des: 'Armenian Dram',
    pais: 'Armenia',
    mon_est: 1,
  },
  {
    codigo: 'ANG',
    mon_des: 'Netherlands Antillian Guilder',
    pais: 'Antillas Holandesas',
    mon_est: 1,
  },
  {
    codigo: 'AOA',
    mon_des: 'Kwanza',
    pais: 'Angola',
    mon_est: 1,
  },
  {
    codigo: 'ARS',
    mon_des: 'Argentine Peso',
    pais: 'Argentina',
    mon_est: 1,
  },
  {
    codigo: 'AUD',
    mon_des: 'Australian Dollar',
    pais: 'Australia',
    mon_est: 1,
  },
  {
    codigo: 'AWG',
    mon_des: 'Aruban Guilder',
    pais: 'Aruba',
    mon_est: 1,
  },
  {
    codigo: 'AZN',
    mon_des: 'Azerbaijanian Manat',
    pais: 'Azerbaiyán',
    mon_est: 1,
  },
  {
    codigo: 'BAM',
    mon_des: 'Convertible Marks',
    pais: 'Bosnia y Herzegovina',
    mon_est: 1,
  },
  {
    codigo: 'BBD',
    mon_des: 'Barbados Dollar',
    pais: 'Barbados',
    mon_est: 1,
  },
  {
    codigo: 'BDT',
    mon_des: 'Taka',
    pais: 'Bangladesh',
    mon_est: 1,
  },
  {
    codigo: 'BGN',
    mon_des: 'Bulgarian Lev',
    pais: 'Bulgaria',
    mon_est: 1,
  },
  {
    codigo: 'BHD',
    mon_des: 'Bahraini Dinar',
    pais: 'Bahréin',
    mon_est: 1,
  },
  {
    codigo: 'BIF',
    mon_des: 'Burundi Franc',
    pais: 'Burundi',
    mon_est: 1,
  },
  {
    codigo: 'BMD',
    mon_des: 'Bermudian Dollar (customarily known as Bermuda Dollar)',
    pais: 'Bermudas',
    mon_est: 1,
  },
  {
    codigo: 'BND',
    mon_des: 'Brunei Dollar',
    pais: 'Brunéi Darussalam',
    mon_est: 1,
  },
  {
    codigo: 'BOB',
    mon_des: 'Boliviano',
    pais: 'Bolivia',
    mon_est: 1,
  },
  {
    codigo: 'BOV',
    mon_des: 'Mvdol',
    pais: 'Bolivia',
    mon_est: 1,
  },
  {
    codigo: 'BRL',
    mon_des: 'Brazilian Real',
    pais: 'Brasil',
    mon_est: 1,
  },
  {
    codigo: 'BSD',
    mon_des: 'Bahamian Dollar',
    pais: 'Bahamas',
    mon_est: 1,
  },
  {
    codigo: 'BTN',
    mon_des: 'Ngultrum',
    pais: 'Bután',
    mon_est: 1,
  },
  {
    codigo: 'BWP',
    mon_des: 'Pula',
    pais: 'Botsuana',
    mon_est: 1,
  },
  {
    codigo: 'BYR',
    mon_des: 'Belarussian Ruble',
    pais: 'Bielorrusia',
    mon_est: 1,
  },
  {
    codigo: 'BZD',
    mon_des: 'Belize Dollar',
    pais: 'Belice',
    mon_est: 1,
  },
  {
    codigo: 'CAD',
    mon_des: 'Canadian Dollar',
    pais: 'Canadá',
    mon_est: 1,
  },
  {
    codigo: 'CDF',
    mon_des: 'Congolese Franc',
    pais: 'República Democrática del Congo',
    mon_est: 1,
  },
  {
    codigo: 'CHE',
    mon_des: 'WIR Euro',
    pais: 'Suiza',
    mon_est: 1,
  },
  {
    codigo: 'CHF',
    mon_des: 'Swiss Franc',
    pais: 'Suiza',
    mon_est: 1,
  },
  {
    codigo: 'CHW',
    mon_des: 'WIR Franc',
    pais: 'Suiza',
    mon_est: 1,
  },
  {
    codigo: 'CLF',
    mon_des: 'Unidades de fomento',
    pais: 'Chile',
    mon_est: 1,
  },
  {
    codigo: 'CLP',
    mon_des: 'Chilean Peso',
    pais: 'Chile',
    mon_est: 1,
  },
  {
    codigo: 'CNY',
    mon_des: 'Yuan Renminbi',
    pais: 'China (República Popular)',
    mon_est: 1,
  },
  {
    codigo: 'COP',
    mon_des: 'Colombian Peso',
    pais: 'Colombia',
    mon_est: 1,
  },
  {
    codigo: 'COU',
    mon_des: 'Unidad de Valor Real',
    pais: 'Colombia',
    mon_est: 1,
  },
  {
    codigo: 'CRC',
    mon_des: 'Costa Rican Colon',
    pais: 'Costa Rica',
    mon_est: 1,
  },
  {
    codigo: 'CUC',
    mon_des: 'Peso Convertible',
    pais: 'Cuba',
    mon_est: 1,
  },
  {
    codigo: 'CUP',
    mon_des: 'Cuban Peso',
    pais: 'Cuba',
    mon_est: 1,
  },
  {
    codigo: 'CVE',
    mon_des: 'Cape Verde Escudo',
    pais: 'Cabo Verde',
    mon_est: 1,
  },
  {
    codigo: 'CZK',
    mon_des: 'Czech Koruna',
    pais: 'República Checa',
    mon_est: 1,
  },
  {
    codigo: 'DJF',
    mon_des: 'Djibouti Franc',
    pais: 'Yibuti',
    mon_est: 1,
  },
  {
    codigo: 'DKK',
    mon_des: 'Danish Krone',
    pais: 'Dinamarca',
    mon_est: 1,
  },
  {
    codigo: 'DOP',
    mon_des: 'Dominican Peso',
    pais: 'República Dominicana',
    mon_est: 1,
  },
  {
    codigo: 'DZD',
    mon_des: 'Algerian Dinar',
    pais: 'Argelia',
    mon_est: 1,
  },
  {
    codigo: 'EEK',
    mon_des: 'Kroon',
    pais: 'Estonia',
    mon_est: 1,
  },
  {
    codigo: 'EGP',
    mon_des: 'Egyptian Pound',
    pais: 'Egipto',
    mon_est: 1,
  },
  {
    codigo: 'ERN',
    mon_des: 'Nakfa',
    pais: 'Eritrea',
    mon_est: 1,
  },
  {
    codigo: 'ETB',
    mon_des: 'Ethiopian Birr',
    pais: 'Etiopía',
    mon_est: 1,
  },
  {
    codigo: 'EUR',
    mon_des: 'Euro',
    pais: 'Unión Europea',
    mon_est: 1,
  },
  {
    codigo: 'FJD',
    mon_des: 'Fiji Dollar',
    pais: 'Fiyi',
    mon_est: 1,
  },
  {
    codigo: 'FKP',
    mon_des: 'Falkland Islands Pound',
    pais: 'Islas Malvinas',
    mon_est: 1,
  },
  {
    codigo: 'GBP',
    mon_des: 'Pound Sterling',
    pais: 'Reino Unido',
    mon_est: 1,
  },
  {
    codigo: 'GEL',
    mon_des: 'Lari',
    pais: 'Georgia',
    mon_est: 1,
  },
  {
    codigo: 'GHS',
    mon_des: 'Cedi',
    pais: 'Ghana',
    mon_est: 1,
  },
  {
    codigo: 'GIP',
    mon_des: 'Gibraltar Pound',
    pais: 'Gibraltar',
    mon_est: 1,
  },
  {
    codigo: 'GMD',
    mon_des: 'Dalasi',
    pais: 'Gambia',
    mon_est: 1,
  },
  {
    codigo: 'GNF',
    mon_des: 'Guinea Franc',
    pais: 'Guinea',
    mon_est: 1,
  },
  {
    codigo: 'GTQ',
    mon_des: 'Quetzal',
    pais: 'Guatemala',
    mon_est: 1,
  },
  {
    codigo: 'GYD',
    mon_des: 'Guyana Dollar',
    pais: 'Guyana',
    mon_est: 1,
  },
  {
    codigo: 'HKD',
    mon_des: 'Hong Kong Dollar',
    pais: 'Hong Kong',
    mon_est: 1,
  },
  {
    codigo: 'HNL',
    mon_des: 'Lempira',
    pais: 'Honduras',
    mon_est: 1,
  },
  {
    codigo: 'HRK',
    mon_des: 'Croatian Kuna',
    pais: 'Croacia',
    mon_est: 1,
  },
  {
    codigo: 'HTG',
    mon_des: 'Gourde',
    pais: 'Haití',
    mon_est: 1,
  },
  {
    codigo: 'HUF',
    mon_des: 'Forint',
    pais: 'Hungría',
    mon_est: 1,
  },
  {
    codigo: 'IDR',
    mon_des: 'Rupiah',
    pais: 'Indonesia',
    mon_est: 1,
  },
  {
    codigo: 'ILS',
    mon_des: 'New Israeli Sheqel',
    pais: 'Israel',
    mon_est: 1,
  },
  {
    codigo: 'INR',
    mon_des: 'Indian Rupee',
    pais: 'India',
    mon_est: 1,
  },
  {
    codigo: 'IQD',
    mon_des: 'Iraqi Dinar',
    pais: 'Iraq',
    mon_est: 1,
  },
  {
    codigo: 'IRR',
    mon_des: 'Iranian Rial',
    pais: 'Irán',
    mon_est: 1,
  },
  {
    codigo: 'ISK',
    mon_des: 'Iceland Krona',
    pais: 'Islandia',
    mon_est: 1,
  },
  {
    codigo: 'JMD',
    mon_des: 'Jamaican Dollar',
    pais: 'Jamaica',
    mon_est: 1,
  },
  {
    codigo: 'JOD',
    mon_des: 'Jordanian Dinar',
    pais: 'Jordania',
    mon_est: 1,
  },
  {
    codigo: 'JPY',
    mon_des: 'Yen',
    pais: 'Japón',
    mon_est: 1,
  },
  {
    codigo: 'KES',
    mon_des: 'Kenyan Shilling',
    pais: 'Kenia',
    mon_est: 1,
  },
  {
    codigo: 'KGS',
    mon_des: 'Som',
    pais: 'Kirguistán',
    mon_est: 1,
  },
  {
    codigo: 'KHR',
    mon_des: 'Riel',
    pais: 'Camboya',
    mon_est: 1,
  },
  {
    codigo: 'KMF',
    mon_des: 'Comoro Franc',
    pais: 'Comoras',
    mon_est: 1,
  },
  {
    codigo: 'KPW',
    mon_des: 'North Korean Won',
    pais: 'Corea (del Norte)',
    mon_est: 1,
  },
  {
    codigo: 'KRW',
    mon_des: 'Won',
    pais: 'Corea (del Sur)',
    mon_est: 1,
  },
  {
    codigo: 'KWD',
    mon_des: 'Kuwaiti Dinar',
    pais: 'Kuwait',
    mon_est: 1,
  },
  {
    codigo: 'KYD',
    mon_des: 'Cayman Islands Dollar',
    pais: 'Islas Caimán',
    mon_est: 1,
  },
  {
    codigo: 'KZT',
    mon_des: 'Tenge',
    pais: 'Kazajistán',
    mon_est: 1,
  },
  {
    codigo: 'LAK',
    mon_des: 'Kip',
    pais: 'Laos',
    mon_est: 1,
  },
  {
    codigo: 'LBP',
    mon_des: 'Lebanese Pound',
    pais: 'Líbano',
    mon_est: 1,
  },
  {
    codigo: 'LKR',
    mon_des: 'Sri Lanka Rupee',
    pais: 'Sri Lanka',
    mon_est: 1,
  },
  {
    codigo: 'LRD',
    mon_des: 'Liberian Dollar',
    pais: 'Liberia',
    mon_est: 1,
  },
  {
    codigo: 'LSL',
    mon_des: 'Loti',
    pais: 'Lesoto',
    mon_est: 1,
  },
  {
    codigo: 'LTL',
    mon_des: 'Lithuanian Litas',
    pais: 'Lituania',
    mon_est: 1,
  },
  {
    codigo: 'LVL',
    mon_des: 'Latvian Lats',
    pais: 'Letonia',
    mon_est: 1,
  },
  {
    codigo: 'LYD',
    mon_des: 'Libyan Dinar',
    pais: 'Libia',
    mon_est: 1,
  },
  {
    codigo: 'MAD',
    mon_des: 'Moroccan Dirham',
    pais: 'Marruecos',
    mon_est: 1,
  },
  {
    codigo: 'MDL',
    mon_des: 'Moldovan Leu',
    pais: 'Moldavia',
    mon_est: 1,
  },
  {
    codigo: 'MGA',
    mon_des: 'Malagasy Ariary',
    pais: 'Madagascar',
    mon_est: 1,
  },
  {
    codigo: 'MKD',
    mon_des: 'Denar',
    pais: 'Macedonia',
    mon_est: 1,
  },
  {
    codigo: 'MMK',
    mon_des: 'Kyat',
    pais: 'Myanmar (Birmania)',
    mon_est: 1,
  },
  {
    codigo: 'MNT',
    mon_des: 'Tugrik',
    pais: 'Mongolia',
    mon_est: 1,
  },
  {
    codigo: 'MOP',
    mon_des: 'Pataca',
    pais: 'Macao',
    mon_est: 1,
  },
  {
    codigo: 'MRO',
    mon_des: 'Ouguiya',
    pais: 'Mauritania',
    mon_est: 1,
  },
  {
    codigo: 'MUR',
    mon_des: 'Mauritius Rupee',
    pais: 'Mauricio',
    mon_est: 1,
  },
  {
    codigo: 'MVR',
    mon_des: 'Rufiyaa',
    pais: 'Maldivas',
    mon_est: 1,
  },
  {
    codigo: 'MWK',
    mon_des: 'Kwacha',
    pais: 'Malaui',
    mon_est: 1,
  },
  {
    codigo: 'MXN',
    mon_des: 'Mexican Peso',
    pais: 'México',
    mon_est: 1,
  },
  {
    codigo: 'MXV',
    mon_des: 'Mexican Unidad de Inversion (UDI)',
    pais: 'México',
    mon_est: 1,
  },
  {
    codigo: 'MYR',
    mon_des: 'Malaysian Ringgit',
    pais: 'Malasia',
    mon_est: 1,
  },
  {
    codigo: 'MZN',
    mon_des: 'Metical',
    pais: 'Mozambique',
    mon_est: 1,
  },
  {
    codigo: 'NAD',
    mon_des: 'Namibia Dollar',
    pais: 'Namibia',
    mon_est: 1,
  },
  {
    codigo: 'NGN',
    mon_des: 'Naira',
    pais: 'Nigeria',
    mon_est: 1,
  },
  {
    codigo: 'NIO',
    mon_des: 'Cordoba Oro',
    pais: 'Nicaragua',
    mon_est: 1,
  },
  {
    codigo: 'NOK',
    mon_des: 'Norwegian Krone',
    pais: 'Noruega',
    mon_est: 1,
  },
  {
    codigo: 'NPR',
    mon_des: 'Nepalese Rupee',
    pais: 'Nepal',
    mon_est: 1,
  },
  {
    codigo: 'NZD',
    mon_des: 'New Zealand Dollar',
    pais: 'Nueva Zelanda',
    mon_est: 1,
  },
  {
    codigo: 'OMR',
    mon_des: 'Rial Omani',
    pais: 'Omán',
    mon_est: 1,
  },
  {
    codigo: 'PAB',
    mon_des: 'Balboa',
    pais: 'Panamá',
    mon_est: 1,
  },
  {
    codigo: 'PEN',
    mon_des: 'Nuevo Sol o Sol',
    pais: 'Perú',
    mon_est: 1,
  },
  {
    codigo: 'PGK',
    mon_des: 'Kina',
    pais: 'Papúa Nueva Guinea',
    mon_est: 1,
  },
  {
    codigo: 'PHP',
    mon_des: 'Philippine Peso',
    pais: 'Filipinas',
    mon_est: 1,
  },
  {
    codigo: 'PKR',
    mon_des: 'Pakistan Rupee',
    pais: 'Pakistán',
    mon_est: 1,
  },
  {
    codigo: 'PLN',
    mon_des: 'Zloty',
    pais: 'Polonia',
    mon_est: 1,
  },
  {
    codigo: 'PYG',
    mon_des: 'Guarani',
    pais: 'Paraguay',
    mon_est: 1,
  },
  {
    codigo: 'QAR',
    mon_des: 'Qatari Rial',
    pais: 'Qatar',
    mon_est: 1,
  },
  {
    codigo: 'RON',
    mon_des: 'New Leu',
    pais: 'Rumania',
    mon_est: 1,
  },
  {
    codigo: 'RSD',
    mon_des: 'Serbian Dinar',
    pais: 'Serbia',
    mon_est: 1,
  },
  {
    codigo: 'RUB',
    mon_des: 'Russian Ruble',
    pais: 'Rusia',
    mon_est: 1,
  },
  {
    codigo: 'RWF',
    mon_des: 'Rwanda Franc',
    pais: 'Ruanda',
    mon_est: 1,
  },
  {
    codigo: 'SAR',
    mon_des: 'Saudi Riyal',
    pais: 'Arabia Saudita',
    mon_est: 1,
  },
  {
    codigo: 'SBD',
    mon_des: 'Solomon Islands Dollar',
    pais: 'Islas Salomón',
    mon_est: 1,
  },
  {
    codigo: 'SCR',
    mon_des: 'Seychelles Rupee',
    pais: 'Seychelles',
    mon_est: 1,
  },
  {
    codigo: 'SDG',
    mon_des: 'Sudanese Pound',
    pais: 'Sudán',
    mon_est: 1,
  },
  {
    codigo: 'SEK',
    mon_des: 'Swedish Krona',
    pais: 'Suecia',
    mon_est: 1,
  },
  {
    codigo: 'SGD',
    mon_des: 'Singapore Dollar',
    pais: 'Singapur',
    mon_est: 1,
  },
  {
    codigo: 'SHP',
    mon_des: 'Saint Helena Pound',
    pais: 'Santa Helena',
    mon_est: 1,
  },
  {
    codigo: 'SLL',
    mon_des: 'Leone',
    pais: 'Sierra Leona',
    mon_est: 1,
  },
  {
    codigo: 'SOS',
    mon_des: 'Somali Shilling',
    pais: 'Somalia',
    mon_est: 1,
  },
  {
    codigo: 'SRD',
    mon_des: 'Surinam Dollar',
    pais: 'Surinam',
    mon_est: 1,
  },
  {
    codigo: 'STD',
    mon_des: 'Dobra',
    pais: 'Santo Tomé y Príncipe',
    mon_est: 1,
  },
  {
    codigo: 'SVC',
    mon_des: 'El Salvador Colon',
    pais: 'El Salvador',
    mon_est: 1,
  },
  {
    codigo: 'SYP',
    mon_des: 'Syrian Pound',
    pais: 'Siria',
    mon_est: 1,
  },
  {
    codigo: 'SZL',
    mon_des: 'Lilangeni',
    pais: 'Suazilandia',
    mon_est: 1,
  },
  {
    codigo: 'THB',
    mon_des: 'Baht',
    pais: 'Tailandia',
    mon_est: 1,
  },
  {
    codigo: 'TJS',
    mon_des: 'Somoni',
    pais: 'Tayikistán',
    mon_est: 1,
  },
  {
    codigo: 'TMT',
    mon_des: 'Manat',
    pais: 'Turkmenistán',
    mon_est: 1,
  },
  {
    codigo: 'TND',
    mon_des: 'Tunisian Dinar',
    pais: 'Túnez',
    mon_est: 1,
  },
  {
    codigo: 'TOP',
    mon_des: "Pa'anga",
    pais: 'Tonga',
    mon_est: 1,
  },
  {
    codigo: 'TRY',
    mon_des: 'Turkish Lira',
    pais: 'Turquía',
    mon_est: 1,
  },
  {
    codigo: 'TTD',
    mon_des: 'Trinidad and Tobago Dollar',
    pais: 'Trinidad y Tobago',
    mon_est: 1,
  },
  {
    codigo: 'TWD',
    mon_des: 'New Taiwan Dollar',
    pais: 'Taiwán',
    mon_est: 1,
  },
  {
    codigo: 'TZS',
    mon_des: 'Tanzanian Shilling',
    pais: 'Tanzania',
    mon_est: 1,
  },
  {
    codigo: 'UAH',
    mon_des: 'Hryvnia',
    pais: 'Ucrania',
    mon_est: 1,
  },
  {
    codigo: 'UGX',
    mon_des: 'Uganda Shilling',
    pais: 'Uganda',
    mon_est: 1,
  },
  {
    codigo: 'USD',
    mon_des: 'US Dollar',
    pais: 'Estados Unidos (EEUU)',
    mon_est: 1,
  },
  {
    codigo: 'USN',
    mon_des: 'US Dollar (Next day)',
    pais: 'Estados Unidos (EEUU)',
    mon_est: 1,
  },
  {
    codigo: 'USS',
    mon_des: 'US Dollar (Same day)',
    pais: 'Estados Unidos (EEUU)',
    mon_est: 1,
  },
  {
    codigo: 'UYI',
    mon_des: 'Uruguay Peso en Unidades Indexadas',
    pais: 'Uruguay',
    mon_est: 1,
  },
  {
    codigo: 'UYU',
    mon_des: 'Peso Uruguayo',
    pais: 'Uruguay',
    mon_est: 1,
  },
  {
    codigo: 'UZS',
    mon_des: 'Uzbekistan Sum',
    pais: 'Uzbekistán',
    mon_est: 1,
  },
  {
    codigo: 'VEF',
    mon_des: 'Bolivar Fuerte',
    pais: 'Venezuela',
    mon_est: 1,
  },
  {
    codigo: 'VND',
    mon_des: 'Dong',
    pais: 'Vietnam',
    mon_est: 1,
  },
  {
    codigo: 'VUV',
    mon_des: 'Vatu',
    pais: 'Vanuatu',
    mon_est: 1,
  },
  {
    codigo: 'WST',
    mon_des: 'Tala',
    pais: 'Samoa del Oeste',
    mon_est: 1,
  },
  {
    codigo: 'XAF',
    mon_des: 'CFA Franc BEAC ‡',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XAG',
    mon_des: 'Silver',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XAU',
    mon_des: 'Gold',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XBA',
    mon_des: 'Bond Markets Units European Composite Unit (EURCO)',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XBB',
    mon_des: 'European Monetary Unit (E.M.U.-6)',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XBC',
    mon_des: 'European Unit of Account 9(E.U.A.-9)',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XBD',
    mon_des: 'European Unit of Account 17(E.U.A.-17)',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XCD',
    mon_des: 'East Caribbean Dollar',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XDR',
    mon_des: 'SDR',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XFU',
    mon_des: 'UIC-Franc',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XOF',
    mon_des: 'CFA Franc BCEAO †',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XPD',
    mon_des: 'Palladium',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XPF',
    mon_des: 'CFP Franc',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'XPT',
    mon_des: 'Platinum',
    pais: '-',
    mon_est: 1,
  },
  {
    codigo: 'YER',
    mon_des: 'Yemeni Rial',
    pais: 'Yemen',
    mon_est: 1,
  },
  {
    codigo: 'ZAR',
    mon_des: 'Rand',
    pais: 'Sudáfrica',
    mon_est: 1,
  },
  {
    codigo: 'ZMK',
    mon_des: 'Zambian Kwacha',
    pais: 'Zambia',
    mon_est: 1,
  },
  {
    codigo: 'ZWL',
    mon_des: 'Zimbabwe Dollar',
    pais: 'Zimbabue',
    mon_est: 1,
  },
];
