export const plan_cuenta = [
  {
    cta_id: 1,
    Descripción: 'Elemento 1: Activo Disponible y Exigible',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 1,
    nivel_descripcion: 'Elemento',
  },
  {
    cta_id: 2,
    Descripción: 'Elemento 2: Activo Realizable',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 1,
    nivel_descripcion: 'Elemento',
  },
  {
    cta_id: 3,
    Descripción: 'Elemento 3: Activo Inmovilizado',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 1,
    nivel_descripcion: 'Elemento',
  },
  {
    cta_id: 5,
    Descripción: 'Elemento 5: Patrimonio Neto',
    clacta_id: 'P',
    nombre_clase: 'Pasivo',
    nivcta_id: 1,
    nivel_descripcion: 'Elemento',
  },
  {
    cta_id: 6,
    Descripción: 'Elemento 6: Gastos por Naturaleza',
    clacta_id: 'N',
    nombre_clase: 'Naturaleza',
    nivcta_id: 1,
    nivel_descripcion: 'Elemento',
  },
  {
    cta_id: 10,
    Descripción: 'Efectivo y Equivalente de Efectivo',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 11,
    Descripción: 'Inversiones Financieras',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 12,
    Descripción: 'Cuentas Por Cobrar Comerciales - Terceros',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 13,
    Descripción: 'Cuentas Por Cobrar Comerciales - Relacionadas',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 14,
    Descripción: 'Cuentas por Cobrar al Personal, Accionistas y Directores',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 16,
    Descripción: 'Cuentas Por Cobrar Diversas - Terceros',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 17,
    Descripción: 'Cuentas Por Cobrar Diversas - Relacionadas',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 18,
    Descripción: 'Servicios y Otros Contratados por Anticipado',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 19,
    Descripción: 'Estimacion de Cuentas de Cobranza Dudosa',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
  {
    cta_id: 20,
    Descripción: 'Mercaderías',
    clacta_id: 'A',
    nombre_clase: 'Activo',
    nivcta_id: 2,
    nivel_descripcion: 'Cuenta',
  },
];
